### ISSUE TITLE
Rewrite pangolin in rust

### ISSUE THREAD

**Issue by Cackbone** [SalonDesDevs/pangolin#2]
Can you rewrite this game in rust please ?

**Comment by cchudant** [comment]
Agreed. Rust's compilation makes it very easy to make fast and portable games, and its type system makes you very productive and allows you to more easily write bug-free programs.
You should start learning rust, it has very good documentation and an awesome community.
Here is the best tutorial around:
https://doc.rust-lang.org/stable/book/
Join us on #rust on the discord, we will help you get started.
